<a href="https://colab.research.google.com/github/FaiazS/LLM-Fine-Tuning-for-Sentiment-Analysis-Using-QLoRA/blob/main/Fine_Tuned__BERT_LLM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#Installing required Libraries

!pip install tensorflow

!pip install datasets

!pip install transformers

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 487.4/487.4 kB 15.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 10.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 183.9/183.9 kB 17.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.5/143.5 kB 12.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.8/194.8 kB 19.0 MB/s eta 0:00:00
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2025.3.0
    Uninstalling fsspec-2025.3.0:
      Successfully uninstalled fsspec-2025.3.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gcsfs 2025.3.0 requires fsspec==2025.3.0, but you have fsspec 2024.12.0 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cublas-cu12==12.4.5.8; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cublas-cu12 12.5.3.2 which

In [3]:
import tensorflow as tf

from transformers import TFAutoModel, AutoTokenizer

from datasets import load_dataset

In [4]:
#Calling the Model API

bert_model = TFAutoModel.from_pretrained("bert-base-uncased")

bert_tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFBertModel: ['cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.bias']
- This IS expected if you are initializing TFBertModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFBertModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions w

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

In [5]:
#Defining the fine- tuning inputs

fine_tuning_inputs = bert_tokenizer(["Hi there", "I am an Aspiring Engineer", "The name is Faiaz"], padding = True, truncation = True, return_tensors = "tf")

print(fine_tuning_inputs)

{'input_ids': <tf.Tensor: shape=(3, 7), dtype=int32, numpy=
array([[  101,  7632,  2045,   102,     0,     0,     0],
       [  101,  1045,  2572,  2019, 22344,  3992,   102],
       [  101,  1996,  2171,  2003, 26208, 10936,   102]], dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(3, 7), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(3, 7), dtype=int32, numpy=
array([[1, 1, 1, 1, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]], dtype=int32)>}


In [6]:
output_1 = bert_model(fine_tuning_inputs)

print(output_1)

TFBaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=<tf.Tensor: shape=(3, 7, 768), dtype=float32, numpy=
array([[[-0.14789365,  0.3964893 , -0.24775231, ..., -0.12281252,
          0.14289233,  0.3214385 ],
        [ 0.22998449, -0.16025826,  0.88774323, ..., -0.3639866 ,
          0.17502777, -0.09828743],
        [-0.447093  ,  0.20279731, -0.19469813, ...,  0.12965615,
          0.12807491, -0.48188668],
        ...,
        [-0.33207282,  0.22787064,  0.20943958, ..., -0.01931895,
          0.12136832,  0.3419533 ],
        [-0.44987243, -0.06930469,  0.15174896, ...,  0.34769073,
          0.06565805, -0.00998406],
        [-0.3521151 , -0.0996485 ,  0.29120275, ...,  0.1758036 ,
          0.10939115,  0.00387091]],

       [[ 0.0780763 ,  0.30049157, -0.00763385, ..., -0.15519926,
          0.33646315,  0.33645803],
        [ 0.26514998,  0.26925847, -0.33557436, ...,  0.09258042,
          0.8073943 ,  0.03054823],
        [ 0.20549197,  0.5917302 ,  0.04925112, ...

In [7]:
#Loading the dataset for fine_tuning

sentiment_analysis_dataset = load_dataset('SetFit/emotion')

README.md:   0%|          | 0.00/194 [00:00<?, ?B/s]

Repo card metadata block was not found. Setting CardData to empty.


train.jsonl:   0%|          | 0.00/2.23M [00:00<?, ?B/s]

validation.jsonl:   0%|          | 0.00/276k [00:00<?, ?B/s]

test.jsonl:   0%|          | 0.00/279k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/16000 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/2000 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/2000 [00:00<?, ? examples/s]

In [8]:
print(sentiment_analysis_dataset)

DatasetDict({
    train: Dataset({
        features: ['text', 'label', 'label_text'],
        num_rows: 16000
    })
    validation: Dataset({
        features: ['text', 'label', 'label_text'],
        num_rows: 2000
    })
    test: Dataset({
        features: ['text', 'label', 'label_text'],
        num_rows: 2000
    })
})


In [9]:
sentiment_analysis_dataset['train'][3]

{'text': 'i am ever feeling nostalgic about the fireplace i will know that it is still on the property',
 'label': 2,
 'label_text': 'love'}

In [10]:
#Tokenizing the dataset

def tokenize_data(batch):

  return bert_tokenizer(batch["text"], padding = True, truncation = True)

In [11]:
#Converting the Sentiment Analysis Dataset into a Format which is accepted by the BERT Model before we feed it to the latter and begin the custom-training / fine-tuned training process.

sentiment_analysis_dataset_encoded = sentiment_analysis_dataset.map(tokenize_data, batched = True, batch_size = 2000)

Map:   0%|          | 0/16000 [00:00<?, ? examples/s]

Map:   0%|          | 0/2000 [00:00<?, ? examples/s]

Map:   0%|          | 0/2000 [00:00<?, ? examples/s]

In [12]:
print(sentiment_analysis_dataset_encoded)

DatasetDict({
    train: Dataset({
        features: ['text', 'label', 'label_text', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 16000
    })
    validation: Dataset({
        features: ['text', 'label', 'label_text', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 2000
    })
    test: Dataset({
        features: ['text', 'label', 'label_text', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 2000
    })
})


In [13]:
#Installing PyTorch and other required dependencies

!pip install torch

!pip install transformers

!pip install peft datasets

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 4.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 116.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 84.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 54.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 2.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 6.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 12.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 7.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 4.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 45.1 MB/s eta 0:00:00
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstalling nvidia-nvjitlink-cu12-12.5.82:
      Successfully uninstalled nvidia-nvjitli

In [2]:
#Re-loading the dataset

from datasets import load_dataset

dataset = load_dataset('SetFit/emotion')

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Repo card metadata block was not found. Setting CardData to empty.


In [3]:
#Extracting both the Training and the Testing Data from the re-loaded dataset.

training_data = dataset['train']

test_data = dataset['test']

In [4]:
#Tokenization and Model Definition

from transformers import AutoTokenizer

from huggingface_hub import hf_hub_download

import os

import socket

socket.setdefaulttimeout(30)

bert_tokenizer = AutoTokenizer.from_pretrained('bert-base-uncased')

In [5]:
#Tokenizing both the training and testing data

def tokenize(batch):

  return bert_tokenizer(batch['text'], padding = True, truncation = True)

training_dataset = training_data.map(tokenize, batched = True)

testing_dataset = test_data.map(tokenize, batched = True)

Map:   0%|          | 0/2000 [00:00<?, ? examples/s]

In [6]:
#Converting the datasets to PyTorch formats

training_dataset.set_format(type = "torch", columns = ["input_ids", "attention_mask" , "label"])

testing_dataset.set_format(type = "torch", columns = ["input_ids", "attention_mask" , "label"])

In [7]:
#Loading the Pretrained LLM Model for Fine-Tuning

from transformers import AutoModelForSequenceClassification

bert_model = AutoModelForSequenceClassification.from_pretrained("bert-base-uncased", num_labels = 6)  #6 Output Classes.

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [8]:
print(bert_model)

BertForSequenceClassification(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSdpaSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e

In [9]:
#Initializing the Fine-Tuning Process with Parameter Efficient Fine-Tuning Technique -> Low Rank Adaptation(LoRA)

from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training, TaskType

#Configuring Low Rank Adaptation(LoRA)

lora_config = LoraConfig(

                         r = 8, #Low - Rank Adaptation Dimension

                         lora_alpha = 32, #Scaling Factor

                         lora_dropout = 0.1, #Dropout Rate - To prevent overfitting

                         target_modules = ["query", "values"] #Applying LoRa to only Self-Attention layers

)

#Configuring LoRa with the Pre-trained LLM Model

bert_model = prepare_model_for_kbit_training(bert_model)

#Integrating LoRa into the Pre-Trained LLM Model

lora_model = get_peft_model(bert_model, lora_config)

#Printing the LoRa enabled model

lora_model.print_trainable_parameters()

trainable params: 147,456 || all params: 109,634,310 || trainable%: 0.1345


In [10]:
#Initializing the Fine - Tuned Training Process post Fine-Tuning (Applying PEFT Technique - Low Rank Adaptation (LoRa)) on the Pre-trained LLM

from transformers import TrainingArguments, Trainer

#Configuration class that defines how the Training should happen.

training_args = TrainingArguments(

                                        output_dir = "./model_checkpoints",  #Where to save model

                                        num_train_epochs = 3, #Training for 3 epochs

                                        per_device_train_batch_size = 16,  # 16 samples per CPU/GPU

                                        eval_strategy ="epoch", #Evaluation after every epoch

                                        save_strategy = "epoch", #Saving model after every epoch

                                        logging_steps = 10, #Log training metrics every 10 steps

                                        fp16 = True, #Use mixed precision for faster training

                                        save_total_limit = 3,

                                        disable_tqdm = False,

                                        #load_best_model_at_end=True,

                                        #metric_for_best_model = "accuracy",

                                        greater_is_better = True,

                                        report_to = ["wandb"]

)

#A high level class that automates training, evaluation and saving models.
#It wraps around your model and dataset, handling:

# 1 - Training loops

# 2 - Evaluation during training

# 3 - Model saving and checkpointing


lora_model_trainer = Trainer(

                             model = lora_model,

                             args = training_args,

                             train_dataset = training_dataset,

                             eval_dataset = testing_dataset,

                             tokenizer = bert_tokenizer,


)

lora_model_trainer.can_return_loss = True

lora_model_trainer.train()

lora_model_trainer.evaluate()

lora_model_trainer.save_model()

<ipython-input-10-6b7091e4e798>:47: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  lora_model_trainer = Trainer(
No label_names provided for model class `PeftModel`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
wandb: WARNING The `run_name` is currently set to the same value as `TrainingArguments.output_dir`. If this was not intended, please specify a different run name by setting the `TrainingArguments.run_name` parameter.
wandb: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more information.
wandb: Currently logged in as: faiazrex8 (faiazrex8-scaler) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin


In [22]:
!pip install bitsandbytes

In [23]:
!pip install transformers --upgrade

!pip install bitsandbytes --upgrade

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.2/10.2 MB 39.0 MB/s eta 0:00:00
  Attempting uninstall: transformers
    Found existing installation: transformers 4.49.0
    Uninstalling transformers-4.49.0:
      Successfully uninstalled transformers-4.49.0


In [11]:
#Applying Quantized Low Rank Adaptation(Q-LoRA) Parameter Efficient Fine Tuning Technique

from transformers import BitsAndBytesConfig

import torch

#Applying 4-bit Quantization to Optimize Memory Usage
bnb_config = BitsAndBytesConfig(

                              load_in_4bit = True,  #Enabling 4-bit Quantization

                              bnb_4bit_compute_dtype = torch.float16, #Computing in float16

                              bnb_4bit_use_double_quant = True #Applying Double Quantization for greater efficiency

)

#Configuring Q-LoRA to the Pre-trained LLM Model

bert_model = AutoModelForSequenceClassification.from_pretrained('bert-base-uncased', num_labels = 6, quantization_config = bnb_config)

#Pre-trained LLM Model post applying Quantized Low Rank Adaptation(Q-LoRA) Parameter Efficient Fine Tuning Technique

q_lora_model = get_peft_model(bert_model, lora_config)

#Displaying the Updated Trainable Parameter Details of the Pre-Trained LLM

q_lora_model.print_trainable_parameters()

`low_cpu_mem_usage` was None, now default to True since model is quantized.
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


trainable params: 147,456 || all params: 109,634,310 || trainable%: 0.1345


In [12]:
#Integration and Configuration Via Pipelining

from transformers import pipeline

sentiment_classifier = pipeline("text-classification", model = "google-bert/bert-base-uncased")

print(sentiment_classifier("I am very excited to acquire new skills"))

print(sentiment_classifier("I am really enjoying the newly acquired skills"))

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at google-bert/bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Device set to use cuda:0


[{'label': 'LABEL_0', 'score': 0.5467879772186279}]
[{'label': 'LABEL_0', 'score': 0.5317761301994324}]
